<?php

# Frases para utilização na Geração de Valeriano

$phrase = array(
'Nyke Daenerys Jelmāzmo hen Targārio Lentrot, hen Valyrio Uēpo ānogar iksan. Valyrio muño ēngos ñuhys issa.',
'Zaldrizes buzdari iksos daor.',
'Valar Morgulis.',
'Dovaogēdys! Naejot memēbātās! Kelītīs! Nyke Daenerys Jelmāzmo hen Targārio Lentrot, hen Valyrio Uēpo ānogar iksan.' ,
'Valyrio muño ēngos ñuhys issa. Dovaogēdys! Āeksia ossēnātās, menti ossēnātās, qilōni pilos lue vale tolvie ossēnātās',
'riñe dōre ōdrikātās. Urnet luo buzdaro tolvio belma pryjātās!',
'Zaldrīzes buzdari iksos daor',
'lanti vali lantyz azantyssy lanta dōra lantra hāedri',
'mēriar lentun Targārio Lentrot Kelītīs mēre mentyr',
'Nyke Daenerys Jelmāzmo hen Targārio Lentrot, hen Valyrio Uēpo ānogār iksan.',
'Aōhoso ziry rijībiā, se ñuhoso ziry rijībin',
'Jaehossi Uēpossi Arlȳssī',
'Lo ziry arlī jaelāt, jemēlo syt ziry mazemagon jemo bēvilza.',
'Morghot nēdyssy sesīr zūgusy azantys vestras.',
'Kesrio syt bantis zōbrie issa se ossȳngnoti lēdys.',
'Urnet luo buzdaro tolvio belma pryjātās!',
'Belmurtī ivestrās kesīr pōnte jiōrinna',
'Biarior Arlior Jēdari!',
'Yn aderī, mōrī, aōt māzīli se hēnkirī īlvi biarvī manaerili.',
'Bisi vali īlvyz zentyssy issi.',
'Lodaor hēnkos vējose hae Astaprot Yunkai botilza',
'Skoroso jemēle brōzāt?',
'Zaldrīzes buzdari iksos daor.',
'Yne sytivīlībilāt? Hae dāero valoti?',
'Dāerves jevys tepagon yne sytilībos daor.',
'Kastāmiro Damior',
'Kostilus jevi āeksia yno bē pirtra jemot vestretis, iā daoruni jemot vestretis.',
'daorys ziry ōdrikilza.',
'Ziry kivio dārilaros issa, se zȳhon suvio perzō vāedar issa.',
'Dāria Sikudo Dārȳti Vestero.',
'Roberti Dāri zȳhi nekēpti se Āeksiot Ōño jemagon.',
'Tymptir Dēmalȳti',
'Vala Aero syt rōbra derēbza.',
'Astaprot dohaertrossa sīr yno inkot iōrzi, dāeri.',
'Dōrior dārion udrirzi mijessis.',
'Mirri ōdria uēpi dōrī drējī zgiēñisi.',
'Daenerys Targarien, Jelmazmo, Dorzalty, Dāria Sikudo Dārȳti Vestero, Muña Zaldrizoti.',
'Dovaogēdys! Naejot memēbātās!',
'Dārys issa vestris, se prūmio ñuho konir drējior issa.',
'Mirri ōdria uēpi dōrī drējī zgiēñisi.',
'Voktys Eglie aōt gaomilaksir teptas.',
'Vala egromy rōbir ezīmza.',
'Sparos ēlī morghūlilza?',
'Olvie hen embraro tolmiot nykēlot avy ivestragon issa.',
'Valyrio muño ēngos ñuhys issa.',
'Quptenkos Ēngoso ȳdrassis?',
'Dāervose jevosy yne enkot daor.',
'Skoros ynot epilu?',
'Āeksiot zȳhon vaoreznon jepin, se ziksoso udlissis.',
'Skorī dēmalȳti tymptir tymis, ērinis iā morghūlis.',
'Vala egromy rōbir ezīmza.',
'Gadbag aōhe qrīdrughās.',
'Mentyri idañe jevi ivestrilātās keskydoso gaomagon.',
'Voktys Eglie aōt gaomilaksir teptas.',
'Se dāeri vali pōntalo syt gaomoti iderēbzi.',
'Lannister va moriot zyha gēlȳnī addemmis.',
'Geltī aōhe nādīnās.',
'Qilōnario Geron.',
'Keso glaesot iderēptot daor.',
'Skoriot daorys gō istas nēdenkirī jagon.',
'Gryves se Riña Litse.',
'Se jevo qrinuntoti pōjor gūrotriri maghan.',
'Yne sytivīlībilāt? Hae dāero valoti?',
'Valar limassis, hāedus. Valar limassis.',
'Jenti jevi jemēle iderēbilātās, qogrondo jevo hēdrȳ.',
'Hembar Yunkaihot istan.',
'Nyke Daenerys Jelmāzmo hen Targārio Lentrot, hen Valyrio Uēpo ānogār iksan.',
'Yn aderī, mōrī, aōt māzīli se hēnkirī īlvi biarvī manaerili.',
'Lodaor hēnkos vējose hae Astaprot Yunkai botilza.',
'Henujagon jaelza lua vala mirre henujagon kostas.',
'Hēzīr, brōza jevi jemēle iderēbilātās.',
'Mentyri idañe jevi ivestrilātās keskydoso gaomagon.',
'Lo jention mirre nūmāzme ēza, iderenna qopsa verdagon issa.',
'Vīlībāzmosa iderennī emilun.',
'Kesrio syt bantis zōbrie issa se ossȳngnoti lēdys.',
'Āeksio yne ilīritas.',
'Astaprot dohaertrossa sīr yno inkot iōrzi, dāeri',
'Henujagon jaelza lua vala mirre henujagon kostas.',
'Jaehossi Uēpossi Arlȳssī.',
'Sesīr īlot jagon!',
'Jaehossi Uēpossi Arlȳssī.',
'Biarior Arlior Jēdari!',
'Āeksios, aōhos ōñoso īlōn jehikās.',
'Nyke Daenerys Jelmāzmo hen Targārio Lentrot.',
'Udra jelmior issi.',
'Roberti Dāri zȳhi nekēpti se Āeksiot Ōño jemagon.',
'Lo jention mirre nūmāzme ēza, iderenna qopsa verdagon issa.',
'Jentys Dovaogēdyro syt iksā.',
'Va oktio remȳti vale jikās.',
'Belmurtī ivestrās kesīr pōnte jiōrinna se pōjon obūljarion mazōrīnna.',
'Quptyssy pontālī johegzi se jomōzū.',
'Sesīr Urnēbion Zȳhon Keliton Issa. ',
'Kesys ondor avy sytilībus daor.',
'Belmurtī ivestrās kesīr pōnte jiōrinna.',
'Mentyri idañe jevi ivestrilātās keskydoso gaomagon.',
'Jemot kivio ñuhe tepan',
'Konir sagon kostos daor.',
'Kostilus jevi āeksia yno bē pirtra jemot vestretis. ',
'Mittys iksā. Āeksia tolī kostōbi issi.',
'Tubī hae kesīr sittāks, sesīr kirine iksan.',
'Ābre kustittas lua vala raqiros issa.',
'Valar limassis, hāedus',
'Valo lurio vaoresan',
'Lo jention mirre nūmāzme ēza, iderenna qopsa verdagon issa.',
'Lodaor hēnkos vējose hae Astaprot Yunkai botilza.',
'Udrāzmī jemot maghon daor. Iderennon maghan.',
'Skorion massitas?',
'Belmurtī ivestrās kesĪr pōnte jiōrinna se pōjon obūljarion mazōrīnna.',
'Dovaogēdys! Naejot memēbātās!',
'Mentyri idañe jevi ivestrilātās keskydoso gaomagon.',
'Dāerves jevys tepagon yne sytilībos daor. Jemēle mērī sytilības.',
'Mirri ōdria uēpi dōrī drējī zgiēñisi, sepār hen mībājȳr udīr ānogrosa anehussi.',
'Dōrior dārion udrirzi mijessis',
'Henujagon jaelza lua vala mirre henujagon kostas.',
'Muñar aōt teptas lue brōzi, iā mirre tolie iderēbās.',
'Lo jention mirre nūmāzme ēza, iderenna qopsa verdagon issa.',
'Jomōzussis lua vala mirros ēngoso ȳdrassigon kostilos daor.',
'Mirri ōdria uēpi dōrī drējī zgiēñisi.',
'Morghot nēdyssy sesīr zūgusy azantys vestras.',
'Muña Zaldrizoti.',
'Muñar aōt teptas lue brōzi, iā mirre tolie iderēbās.',
'Geltī aōhe nādīnās.',
'Dovaogēdys! Naejot memēbātās!',
'Morghot nēdyssy sesīr zūgusy azantys vestras.',
'Mirri ōdria uēpi dōrī drējī zgiēñisi, sepār hen mībājȳr udīr ānogrosa anehussi.',
'Roberti Dāri zȳhi nekēpti se Āeksiot Ōño jemagon.',
'Nykēlo syt ūndon daor luo valzȳro ñōghossi ōressiks.',
'Aōhoso ziry rijībiā, se ñuhoso ziry rijībin.',
'Lo jention mirre nūmāzme ēza, iderenna qopsa verdagon issa.',
'Belmurtī ivestrās kesīr pōnte jiōrinna se pōjon obūljarion mazōrīnna.',
'Mirri ōdria uēpi dōrī drējī zgiēñisi.',
'Olvī voktī Rulloro Qelbriā ūndessun daor.',
'Kesys ondor avy sytilībus daor.',
'Valo ondoso Aerys iderēbaks.',
'Roberti Dāri zȳhi nekēpti se Āeksiot Ōño jemagon.',
'Nykēlo syt ūndon daor luo valzȳro ñōghossi ōressiks.',
'Dovaogēdys! Āeksia ossēnātās, menti ossēnātās!',
'Kesrio syt bantis zōbrie issa se ossȳngnoti lēdys.',
'Jevys qrinuntys jemo paktot issa',
'Kepa zȳhe tale pāsiles.',
'Perzys Ānogār.',
'Kostilus jevi āeksia yno bē pirtra jemot vestretis.',
'Qilōni pilos lue vale tolvie ossēnātās',
'Dārys issa vestris, se prūmio ñuho konir drējior issa.',
'Olvī voktī Rulloro Qelbriā ūndessun daor.',
'Qilōni pilos lue vale tolvie ossēnātās.',
'Jenti jevi jemēle iderēbilātās, qogrondo jevo hēdrȳ',
'Lo jention mirre nūmāzme ēza, iderenna qopsa verdagon issa.',
'Valar Qringaomis.',
'Jevys qrinuntys jemo paktot issa',
'Quptenkos Ēngoso ȳdrassis?',
'Quptyssy pontālī johegzi se jomōzū.',
'Avy jorrāelan.',
'Zūgagon daor, ñuhys raqiros.',
'Va oktio remȳti vale jikās.',
'Ābra kepe rhēdes lua vala raqiros issa.',
'Tolī rhūqo lōtinti, kostilus.',
'Dārys azanti rijas.',
'Aōhoso ziry rijībiā',
'Gryves se Riña Litse.',
'Davido zaldrīzes aōhos zaldrīzose rōvyktys issa.',
'Aōle rūda, nūmāzma issa.',
'Rūkluni ynot teptas lua vala bisy issa.',
'Ȳghāpī īlōn rāelza, kesrio syt lanta iksan, rūso zȳhosy gōvilirose zijo syt pyghas lue prūmie.',
'Gryves se Riña Litse.',
'Sesīr Urnēbion Zȳhon Keliton Issa.',
'Tubī hae kesīr sittāks, sesīr kirine iksan.',
'Yn dāeri vali sīr issi'
);
?>